services:
  app:
    build: .
    container_name: rate-my-supplements
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ratemysupplements.clqqec84qeyc.us-east-2.rds.amazonaws.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ILoveYorkUniversity!

