services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: freshDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # the data is persisted even when the instance is down

  app:
    build: . # build from the image in Dockerfile
    container_name: rate-my-supplements
    ports:
      - "8080:8080"
    depends_on:
      - postgres # ensures the postgres instance is run before my custom image
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/freshDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

volumes:
  postgres-data:
